version: "3.8"

services:
  dcs-postgres:
    image: postgres:15.3-alpine
    container_name: dcs-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  flyway:
    image: flyway/flyway
    depends_on:
      dcs-postgres:
        condition: service_healthy
    command: >
      -url=jdbc:postgresql://dcs-postgres/postgres
      -user=postgres
      -password=password
      -baselineOnMigrate=true
      -schemas=public
      -connectRetries=60
      migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql

  dcs-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: dcs-pgadmin
    restart: always
    depends_on:
      - dcs-postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: user@localhost.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8080:80"
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin

networks:
  default:
    name: bid-hub-network
    external: true
